---
all:
  children:
    debian:
      hosts:
        monitoring-01:
          ansible_host: 192.168.1.87
    docker_hosts:
      hosts:
        monitoring-01: {}
    monitoring:
      hosts:
        monitoring-01: {}
    proxmox_hosts:
      hosts:
        prox:
          ansible_host: 192.168.1.1
    tailscale:
      hosts:
        tailscale-01:
          ansible_host: 192.168.1.2
    node_exporter_hosts:
      hosts:
        tailscale-01: {}
