---
all:
  children:
    debian:
      hosts:
        monitoring-01:
          ansible_host: 192.168.1.87
    docker_hosts:
      hosts:
        monitoring-01: {}
    monitoring:
      hosts:
        monitoring-01: {}
