---
all:
  children:
    debian:
      hosts:
        backup-01:
          ansible_host: 192.168.1.4
        monitoring-01:
          ansible_host: 192.168.1.87
        proxy-01:
          ansible_host: 192.168.1.3
        vaultwarden-01:
          ansible_host: 192.168.1.5
    docker_hosts:
      hosts:
        monitoring-01: {}
        vaultwarden-01: {}
    proxy:
      hosts:
        proxy-01: {}
    alpine:
      hosts:
        adguard-01:
          ansible_host: 192.168.1.252
    monitoring:
      hosts:
        monitoring-01: {}
    adguard:
      hosts:
        adguard-01: {}
    vaultwarden:
      hosts:
        vaultwarden-01: {}
    backup:
      hosts:
        backup-01: {}
    backup_source_export_hosts:
      hosts:
        adguard-01: {}
        proxy-01: {}
        monitoring-01: {}
        vaultwarden-01: {}
    proxmox_hosts:
      hosts:
        prox:
          ansible_host: 192.168.1.1
    tailscale:
      hosts:
        tailscale-01:
          ansible_host: 192.168.1.2
    node_exporter_hosts:
      hosts:
        backup-01: {}
        tailscale-01: {}
        adguard-01: {}
        proxy-01: {}
        vaultwarden-01: {}
